const bankNames = [
    "Industrial & Commercial Bank of China",
    "Agricultural Bank of China",
    "China Construction Bank Corp",
    "Bank of China",
    "Banco Santander",
    "Groupe BPCE",
    "Societe Generale",
    "Barclays",
    "Deutsche Bank AG",
    "Postal Savings Bank of China",
    "Bank of Communications",
    "Royal Bank of Canada",
    "TD Bank",
    "Lloyds Banking Group",
    "Royal Bank of Scotland plc",
    "China Merchants Bank Company Limited",
    "UniCredit S.p.A.",
    "Norinchukin Bank",
    "UBS Group AG",
    "China Minsheng Banking Corporation",
    "Bank of Nova Scotia",
    "Credit Suisse",
    "Intesa Sanpaolo",
    "China CITIC Bank Corp",
    "Standard Chartered Plc",
    "BBVA",
    "Rabobank Group",
    "Credit Mutuel",
    "Bank of Montreal",
    "Nordea Bank AB",
    "Commonwealth Bank of Australia",
    "Westpac Banking",
    "Resona Holdings, Inc.",
    "Danske Bank",
    "National Australia Bank",
    "Commerzbank",
    "Natixis",
    "Sberbank",
    "Canadian Imperial Bank of Commerce",
    "Bank of New York Mellon Corporation",
    "U.S. Bank",
    "ABN AMRO Bank",
    "Capital One",
    "Nomura Holdings, Inc.",
    "SEB Group",
    "OCBC Bank",
    "DNB ASA",
    "Banco Bradesco",
    "State Street Corporation",
    "Bank of Shanghai",
    "UOB Group",
    "Banco de Sabadell",
    "First Abu Dhabi Bank",
    "ICICI Bank",
    "Maybank",
    "Dexia SA",
    "National Bank of Canada",
    "Banco BPM S.p.A.",
    "KeyCorp",
    "Huntington Bancshares Inc.",
    "Northern Trust",
    "Bank of Ireland",
    "Macquarie",
    "M&T Bank",
    "CIMB Group",
    "Emirates NBD",
    "Korea Post",
    "CITIC Securities",
    "Deka Group",
    "AMP Ltd",
    "National Bank of Kuwait",
    "Bangkok Bank",
    "Siam Commercial Bank",
    "Shinsei Bank",
    "Zions Bancorp",
    "National Bank of Greece",
    "Chang Hwa Commercial Bank",
    "Kuwait Finance House",
    "Akbank",
    "Deutsche Pfandbriefbank Group",
    "Dubai Islamic Bank",
    "Novo Banco, S.A.",
    "Mitsubishi UFJ Lease and Finance Company",
    "Riyad Bank",
    "East West Bancorp",
    "Bank Pekao S.A.",
    "Aozora Bank",
    "Mashreqbank",
    "Banque Misr",
    "Commercial Bank of Qatar",
    "Bank of Queensland",
    "Halkbank",
    "China International Capital Corporation",
    "Tejarat Bank",
    "Alinma Bank",
    "Vontobel Holding AG",
    "Credit Bank of Moscow",
    "Bank Muscat",
    "Gulf International Bank",
    "Arab Banking Corporation"
]

module.exports = bankNames;